### ISSUE TITLE
Live2D Inc.: Regarding Cubism 3.0 SDK Core on this repository

### ISSUE THREAD

**Issue by itoh-at-live2d-com** [asfdfdfd/renpy-live2d#1]
Dear  @asfdfdfd 

Thank you so much for your contribution. It is very exciting to see a Live2D expert like you create unique and useful Framework.

However, we noticed that Cubism 3.0 SDK Core has been redistributed on this repository for the Framework. It is prohibited by our SDK regulation to redistribute the Core. Therefore we'd like you to delete the Core from this repository and ask your end users to download Live2D Native SDK from our official GitHub repository for the implement.
https://live2d.github.io/index.html#native

Again, we trully appreciate your devotion to Live2D community.

Thank you for your understanding.

**Comment by asfdfdfd** [comment]
Done
