### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by asfdfdfd** [asfdfdfd/renpy-live2d#2]
Windows support is missing because Live2D Core does not have precompiled library for MSVC9 that is required for building Python modules for RenPy on Windows.

**Comment by asfdfdfd** [comment]
@itoh-at-live2d-com
@ono-at-live2d-com

Are you able to provide precompiled Core for MSVC9?

**Comment by itoh-at-live2d-com** [comment]
Hi @asfdfdfd ,

Now we are working on this. However, it seems take few times a little more. It would be much appreciated if you could wait a bit.

Thank you so much for your patience.

Sincerely,

**Comment by asfdfdfd** [comment]
Thank you, @itoh-at-live2d-com.

I appreciate that you have found time for this task.

Looking forward! 🍾

**Comment by itoh-at-live2d-com** [comment]
@asfdfdfd 

Dynamic link library of Cubism Core has been added on Cubism SDK for Native.
To download, click "Cubism SDK for Native" in this link.
https://live2d.github.io/

**Comment by asfdfdfd** [comment]
@itoh-at-live2d-com 

Thanks! I'll try it and give feedback.

**Comment by asfdfdfd** [comment]
@itoh-at-live2d-com 

I've tried your changes and sent to other users to test. It seems that Windows support works. Great job!

I'm closing this task but will use it later if something will be broken in Windows support.
